repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        exclude: ^node_modules/
        args: [ --fix ]
      - id: ruff-format
        exclude: ^node_modules/


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    - id: mypy
      exclude: ^node_modules/
      args: [--check-untyped-def, --ignore-missing-import]


  - repo: local
    hooks:
      - id: vulture
        exclude: ^(databricks)/.*\.py$
        name: vulture
        entry: vulture
        language: python
        types: [python]
        args: [--min-confidence, "70"]